# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/admxf/Cmake/cmake_planning_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/admxf/Cmake/cmake_planning_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/admxf/Cmake/cmake_planning_test/CMakeFiles /home/admxf/Cmake/cmake_planning_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/admxf/Cmake/cmake_planning_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named planning_main

# Build rule for target.
planning_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 planning_main
.PHONY : planning_main

# fast build rule for target.
planning_main/fast:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/build
.PHONY : planning_main/fast

planning_main.o: planning_main.cpp.o

.PHONY : planning_main.o

# target to build an object file
planning_main.cpp.o:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/planning_main.cpp.o
.PHONY : planning_main.cpp.o

planning_main.i: planning_main.cpp.i

.PHONY : planning_main.i

# target to preprocess a source file
planning_main.cpp.i:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/planning_main.cpp.i
.PHONY : planning_main.cpp.i

planning_main.s: planning_main.cpp.s

.PHONY : planning_main.s

# target to generate assembly for a file
planning_main.cpp.s:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/planning_main.cpp.s
.PHONY : planning_main.cpp.s

pnc_map.o: pnc_map.cpp.o

.PHONY : pnc_map.o

# target to build an object file
pnc_map.cpp.o:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/pnc_map.cpp.o
.PHONY : pnc_map.cpp.o

pnc_map.i: pnc_map.cpp.i

.PHONY : pnc_map.i

# target to preprocess a source file
pnc_map.cpp.i:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/pnc_map.cpp.i
.PHONY : pnc_map.cpp.i

pnc_map.s: pnc_map.cpp.s

.PHONY : pnc_map.s

# target to generate assembly for a file
pnc_map.cpp.s:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/pnc_map.cpp.s
.PHONY : pnc_map.cpp.s

process.o: process.cpp.o

.PHONY : process.o

# target to build an object file
process.cpp.o:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/process.cpp.o
.PHONY : process.cpp.o

process.i: process.cpp.i

.PHONY : process.i

# target to preprocess a source file
process.cpp.i:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/process.cpp.i
.PHONY : process.cpp.i

process.s: process.cpp.s

.PHONY : process.s

# target to generate assembly for a file
process.cpp.s:
	$(MAKE) -f CMakeFiles/planning_main.dir/build.make CMakeFiles/planning_main.dir/process.cpp.s
.PHONY : process.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... planning_main"
	@echo "... edit_cache"
	@echo "... planning_main.o"
	@echo "... planning_main.i"
	@echo "... planning_main.s"
	@echo "... pnc_map.o"
	@echo "... pnc_map.i"
	@echo "... pnc_map.s"
	@echo "... process.o"
	@echo "... process.i"
	@echo "... process.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

